[tool.poetry]
name = "testviz"
version = "0.1.0"
description = "This is the project description."
authors = ["My Name <my-name@my-org.org>"]
license = "MIT"
readme = "README.md"
include = ["README.md", "src/testviz/schema", "project"]

[tool.poetry.scripts]
generate_viz_json = "src.testviz.scripts.generate_json:generate_viz_json"


[tool.poetry.dependencies]
python = "^3.10.1"
linkml-runtime = "^1.1.24"
rdflib = "6.0.0"
pyyaml = "^6.0.1"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry.dev-dependencies]
linkml = "^1.3.5"
mkdocs = "^1.4.2"
mkdocs-material = "^9.0.12"
mkdocs-mermaid2-plugin = "^0.6.0"
schemasheets = "^0.1.14"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.extras]
docs = ["mkdocs-material"]